wrong encode
KenanY/tripcode pull request #73
Opened 2021-05-05 15:39 UTC by iwamizawa-software

now, encode #ﾐﾐ to xZL8eQdH6s
but 8wihCLEUuc is correct

2021-05-05 17:24 UTC, KenanY requested changes
Please add a test case that asserts the expected behavior that this change fixes.

Also the commit message should be amended to be more clear as to what this is fixing and how.

2021-05-05 21:43 UTC, iccanobif commented
I made another pull request https://github.com/KenanY/tripcode/pull/74 including a test case so that it can replace this one.

2021-05-05 21:50 UTC, 2sh commented
Just for clarity, the .split('') seems to have been put there by mistake. Looking at the original commit, I think the intention was to turn the whole hash_table string into an array. '...' + '...'.split('') results in "....,.,.". It's turning the last string into an array and converting it back into a string with commas between the period characters. Your demo page doesn't do this, and so gets the conversion from ﾐﾐ to xZL8eQdH6s correct, and the following code doesn't do it:
https://github.com/crypt3lx2k/Tripcode-Tester/blob/master/src/tripcode.c#L35

2021-05-06 11:59 UTC, iwamizawa-software commented
Please merge https://github.com/KenanY/tripcode/pull/74

2021-05-06 11:59 UTC, closed without merging

2021-05-10 16:54 UTC, KenanY commented
Fix published in v1.3.5.